export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const STORE_INGREDIENTS = "STORE_INGREDIENTS";

export const GET_RECIPES = "GET_RECIPE";
export const STORE_RECIPES = "STORE_RECIPES";

export const GET_RECIPES_BY_NAME = "GET_RECIPES_BY_NAME";

export const STORE_FILTER_INGREDIENTS = "STORE_FILTER_INGREDIENTS";
export const GET_FILTER_INGREDIENTS = "GET_FILTER_INGREDIENTS";

export const GET_SELECTED_RECIPE = "GET_SELECTED_RECIPE";
export const STORE_SELECTED_RECIPE = "STORE_SELECTED_RECIPE";

export const GET_SELECTED_RECIPES_MISSING_INGS =
  "GET_SELECTED_RECIPES_MISSING_INGS";
export const STORE_SELECTED_RECIPES_MISSING_INGS =
  "STORE_SELECTED_RECIPES_MISSING_INGS";

export const STORE_SELECTED_RECIPES_WARNINGS =
  "STORE_SELECTED_RECIPES_WARNINGS";
export const GET_SELECTED_RECIPES_WARNINGS = "GET_SELECTED_RECIPES_WARNINGS";

export const DIET_TYPES = [
  "VEGETARIAN",
  "VEGAN",
  "DIATERY",
  "VITAMIN",
  "LENTEN",
  "GLUTEN_FREE",
  "DAIRY_FREE",
  "REGULAR",
];

export const CUISINE = [
  "SERBIAN",
  "ITALIAN",
  "MEXICAN",
  "SPANISH",
  "FRENCH",
  "CHINESE",
  "INDIAN",
];

export const MEAL_TYPES = [
  "DESSERT",
  "MAIN",
  "APPETIZER",
  "MAINCOURSE",
  "SALAD",
];
