export const GET_ALL_EXERCISES = "GET_ALL_EXERCISES";
export const STORE_ALL_EXERCISES = "STORE_ALL_EXERCISES";

export const GET_WORKOUTS = "GET_WORKOUTS";
export const STORE_WORKOUTS = "STORE_WORKOUTS";

export const WORKOUT_TYPES = ["CARDIO", "STRENGTH", "MIX"];

export const STORE_EXERCISES_FILTER = "GET_EXERCISES_FILTER";
