export const GET_LOGGED_USERS_DATA = "GET_LOGGED_USERS_DATA";
export const STORE_LOGGED_USERS_DATA = "STORE_LOGGED_USERS_DATA";
export const CLEAR_LOGGED_USERS_DATA = "CLEAR_LOGGED_USERS_DATA";

export const GET_MEAL_HISTORY = "GET_MEAL_HISTORY";
export const STORE_MEAL_HISTORY = "STORE_MEAL_HISTORY";

export const GET_ALL_INGREDIENTS = "GET_ALL_INGREDIENTS";
export const STORE_ALL_INGREDIENTS = "STORE_ALL_INGREDIENTS";

export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const STORE_ALL_RECIPES = "STORE_ALL_RECIPES";

export const SAVE_USER_DATA = "SAVE_USER_DATA";

export const GET_RECOMMENDED_CALORIES = "GET_RECOMMENDED_CALORIES";
export const STORE_RECOMMENDED_CALORIES = "STORE_RECOMMENDED_CALORIES";

export const GET_CALORIE_INTAKE = "GET_CALORIE_INTAKE";
export const STORE_CALORIE_INTAKE = "STORE_CALORIE_INTAKE";

export const UPDATE_GOAL = "UPDATE_GOAL";
export const STORE_GOAL = "STORE_GOAL";

export const ADD_HISTORY_MEAL = "ADD_HISTORY_MEAL";

export const STORE_WARNING = "STORE_WARNING";

export const GET_ALL_WORKOUTS = "GET_ALL_WORKOUTS";
export const STORE_ALL_WORKOUTS = "STORE_ALL_WORKOUTS";

export const ACTIVITIES = [
  "VERY_LIGHT",
  "LIGHT",
  "MODERATE",
  "HEAVY",
  "VERY_HEAVY",
];

export const GOALS = [
  "GAIN_WEIGHT",
  "LOSE_WEIGHT",
  "STAGNATE",
  "GAIN_MUSCLE",
  "LOSE_MUSCLE",
];
